# Generated by Django 3.2.11 on 2022-01-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220125_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=70)),
                ('foundation_year', models.DateTimeField(verbose_name='date published')),
                ('musicians', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.musicians')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=70)),
                ('release_year', models.DateTimeField(verbose_name='date published')),
                ('band_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.band')),
            ],
        ),
    ]
